# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: 
          - int
          - stg
          - ppd
          - prd

env:
  myString: value

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonar:
    if: github.event_name == 'push' && github.ref_name == 'main' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    name: sonar
    steps:
      - name: sonar step
        run: echo "the variable is ${{ env.myString }}"

  dev:
    if: github.event_name == 'push' && github.ref_name == 'main' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' )
    needs: sonar
    runs-on: ubuntu-latest
    environment: dev
    name: dev
    steps:
       - name: dev step
         run: echo "[dev]hello world"

  stg:
    if: github.event_name == 'push' && github.ref_name == 'main' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' )
    needs: [sonar, dev]
    runs-on: ubuntu-latest
    environment: stg
    name: stg
    steps:
       - name: stg step
         run: echo "[stg]hello world"

  ppd:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' )
    needs: [sonar, stg]
    runs-on: ubuntu-latest
    environment: ppd
    name: ppd
    steps:
       - name: ppd step
         run: echo "[ppd]hello world"

  prd:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' )
    needs: [sonar, ppd]
    runs-on: ubuntu-latest
    environment: prd
    name: prd
    steps:
      - name: prd step
        run: echo "[prd]hello world"
